package org.is.auth.model;

public enum Permission {
    ENTITY_CREATE,
    ENTITY_READ,
    OWN_ENTITY_UPDATE,
    ALL_ENTITY_UPDATE,
    OWN_ENTITY_DELETE,
    ALL_ENTITY_DELETE,
    ALL_ENTITY_BULK_DELETE,
    OWN_ENTITY_BULK_DELETE,

    ALL_USER_READ,
    ALL_USER_UPDATE,
    ALL_USER_DELETE,
    ALL_USER_BULK_DELETE
}
